/*
 *    Copyright 2017 West Coast Informatics, LLC
 */
package com.wci.umls.server.jpa.model.report;

import java.util.ArrayList;
import java.util.List;

import com.wci.umls.server.jpa.model.ProjectJpa;
import com.wci.umls.server.jpa.model.content.AbstractHasLastModified;
import com.wci.umls.server.jpa.model.helpers.ObjectToStringBridge;
import com.wci.umls.server.model.algo.Project;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlTransient;
import org.hibernate.search.engine.backend.types.Searchable;
import org.hibernate.search.engine.backend.types.Sortable;
import org.hibernate.search.mapper.pojo.bridge.mapping.annotation.ValueBridgeRef;
import org.hibernate.search.mapper.pojo.mapping.definition.annotation.FullTextField;
import org.hibernate.search.mapper.pojo.mapping.definition.annotation.GenericField;
import org.hibernate.search.mapper.pojo.mapping.definition.annotation.Indexed;
import org.hibernate.search.mapper.pojo.mapping.definition.annotation.IndexingDependency;
import org.hibernate.search.mapper.pojo.mapping.definition.annotation.KeywordField;
import org.hibernate.search.mapper.pojo.mapping.definition.annotation.ObjectPath;
import org.hibernate.search.mapper.pojo.mapping.definition.annotation.PropertyValue;


import com.wci.umls.server.helpers.QueryType;
import com.wci.umls.server.model.report.Report;
import com.wci.umls.server.model.report.ReportResult;

/**
 * JPA enabled implementation of {@link Report}.
 */
@Entity
@Table(name = "reports")
@Indexed
@XmlRootElement(name = "report")
public class ReportJpa extends AbstractHasLastModified implements Report {

  /** The id. */
  @TableGenerator(name = "EntityIdGenReport", table = "table_generator_report", pkColumnValue = "Entity")
  @Id
  @GeneratedValue(strategy = GenerationType.TABLE, generator = "EntityIdGenReport")
  private Long id;

  /** The name. */
  @Column(nullable = false)
  private String name;

  /** The auto generated. */
  @Column(nullable = false)
  private boolean autoGenerated;

  /** The query. */
  @Column(nullable = false, length = 10000)
  private String query; // save the query used at the time report was

  /** The query type. */
  @Enumerated(EnumType.STRING)
  @Column(nullable = false)
  private QueryType queryType;

  /** The query result type. */
  @Column(nullable = false)
  private String resultType;

  /** The project. */
  @ManyToOne(targetEntity = ProjectJpa.class, optional = false)
  // @IndexedEmbedded - don't embed up the indexing tree
  private Project project;

  /** The results. */
  @OneToMany(mappedBy = "report", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true, targetEntity = ReportResultJpa.class)
  // @IndexedEmbedded(targetElement = ReportResultJpa.class)
  private List<ReportResult> results = new ArrayList<>();

  // DIFF report stuff
  /** The source reports for a comparison report. */
  @Column(nullable = true)
  private Long report1Id = null;

  /** The report2 id. */
  @Column(nullable = true)
  private Long report2Id = null;

  /** Flags for diff and rate report. */
  @Column(nullable = false)
  private boolean diffReport = false;

  /**
   * Constructors.
   * 
   */

  /**
   * Instantiates a new report jpa.
   */
  public ReportJpa() {
    // do nothing
  }

  /**
   * Instantiates a {@link ReportJpa} from the specified parameters.
   *
   * @param report the report
   * @param collectionsFlag the collections flag
   */
  public ReportJpa(Report report, boolean collectionsFlag) {
    super(report);
    id = report.getId();
    name = report.getName();
    autoGenerated = report.getAutoGenerated();
    query = report.getQuery();
    queryType = report.getQueryType();
    resultType = report.getResultType();
    report1Id = report.getReport1Id();
    report2Id = report.getReport2Id();
    diffReport = report.isDiffReport();
    project = report.getProject();

    if (collectionsFlag) {
      results = new ArrayList<>(report.getResults());
    }
  }

  /* see superclass */
  @Override
  @GenericField(searchable = Searchable.YES,
      valueBridge = @ValueBridgeRef(type = ObjectToStringBridge.class))
  public Long getId() {
    return this.id;
  }

  /* see superclass */
  @Override
  public void setId(Long id) {
    this.id = id;
  }

  /**
   * Gets the name.
   *
   * @return the name
   */
  @FullTextField(analyzer = "noStopWord")
  @KeywordField(name = "nameSort", sortable = Sortable.YES)
  @Override
  public String getName() {
    return name;
  }

  /* see superclass */
  @Override
  public void setName(String name) {
    this.name = name;
  }

  @Override
  @GenericField(searchable = Searchable.YES,
      valueBridge = @ValueBridgeRef(type = ObjectToStringBridge.class))
  public Boolean getAutoGenerated() {
    return autoGenerated;
  }

  @Override
  public void setAutoGenerated(boolean autoGenerated) {
    this.autoGenerated = autoGenerated;
  }

  @Override
  @KeywordField(searchable = Searchable.YES)
  public String getResultType() {
    return resultType;
  }

  @Override
  public void setResultType(String resultType) {
    this.resultType = resultType;
  }

  @Override
  @FullTextField
  public String getQuery() {
    return query;
  }

  @Override
  public void setQuery(String query) {
    this.query = query;
  }

  @Override
  @GenericField(searchable = Searchable.YES,
      valueBridge = @ValueBridgeRef(type = ObjectToStringBridge.class))
  public QueryType getQueryType() {
    return queryType;
  }

  @Override
  public void setQueryType(QueryType queryType) {
    this.queryType = queryType;
  }

  @Override
  @XmlElement(type = ReportResultJpa.class)
  public List<ReportResult> getResults() {
    if (results == null) {
      results = new ArrayList<>();
    }
    return results;
  }

  @Override
  public void setResults(List<ReportResult> results) {
    this.results = results;
  }

  @Override
  @GenericField(searchable = Searchable.YES,
      valueBridge = @ValueBridgeRef(type = ObjectToStringBridge.class))
  public Long getReport1Id() {
    return this.report1Id;
  }

  @Override
  public void setReport1Id(Long reportId) {
    this.report1Id = reportId;

  }

  @Override
  @GenericField(searchable = Searchable.YES,
      valueBridge = @ValueBridgeRef(type = ObjectToStringBridge.class))
  public Long getReport2Id() {
    return this.report2Id;
  }

  @Override
  @GenericField(searchable = Searchable.YES,
          valueBridge = @ValueBridgeRef(type = ObjectToStringBridge.class))
  public void setReport2Id(Long reportId) {
    this.report2Id = reportId;
  }

  @Override
  @GenericField(searchable = Searchable.YES,
      valueBridge = @ValueBridgeRef(type = ObjectToStringBridge.class))
  public boolean isDiffReport() {
    return diffReport;
  }

  @Override
  public void setDiffReport(boolean diffReport) {
    this.diffReport = diffReport;
  }

  /* see superclass */
  @XmlTransient
  @Override
  public Project getProject() {
    return project;
  }

  /* see superclass */
  @Override
  public void setProject(Project project) {
    this.project = project;
  }

  /**
   * Returns the project id. For JAXB
   *
   * @return the project id
   */
  @XmlElement
  @GenericField(searchable = Searchable.YES,
      valueBridge = @ValueBridgeRef(type = ObjectToStringBridge.class))
  @IndexingDependency(derivedFrom = @ObjectPath(@PropertyValue(propertyName = "project")))
  public Long getProjectId() {
    return (project != null) ? project.getId() : 0;
  }

  /**
   * Sets the project id.
   *
   * @param projectId the project id
   */
  @SuppressWarnings("unused")
  private void setProjectId(Long projectId) {
    if (project == null) {
      project = new ProjectJpa();
    }
    project.setId(projectId);
  }

  /* see superclass */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + (autoGenerated ? 1231 : 1237);
    result = prime * result + (diffReport ? 1231 : 1237);
    result = prime * result + ((name == null) ? 0 : name.hashCode());
    result = prime * result + ((query == null) ? 0 : query.hashCode());
    result = prime * result + ((queryType == null) ? 0 : queryType.hashCode());
    result = prime * result + ((report1Id == null) ? 0 : report1Id.hashCode());
    result = prime * result + ((report2Id == null) ? 0 : report2Id.hashCode());
    result =
        prime * result + ((resultType == null) ? 0 : resultType.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    ReportJpa other = (ReportJpa) obj;
    if (autoGenerated != other.autoGenerated)
      return false;
    if (diffReport != other.diffReport)
      return false;
    if (name == null) {
      if (other.name != null)
        return false;
    } else if (!name.equals(other.name))
      return false;
    if (query == null) {
      if (other.query != null)
        return false;
    } else if (!query.equals(other.query))
      return false;
    if (queryType != other.queryType)
      return false;
    if (report1Id == null) {
      if (other.report1Id != null)
        return false;
    } else if (!report1Id.equals(other.report1Id))
      return false;
    if (report2Id == null) {
      if (other.report2Id != null)
        return false;
    } else if (!report2Id.equals(other.report2Id))
      return false;
    if (resultType == null) {
      if (other.resultType != null)
        return false;
    } else if (!resultType.equals(other.resultType))
      return false;
    return true;
  }

}
