#
# Local development overrides
#
deploy.mode=${DEPLOY_MODE:DEV}
base.url=${BASE_URL:http://localhost:${SERVER_PORT:8080}/umls-server-rest}
deploy.title=${DEPLOY_TITLE:Term Server Local}
mail.enabled=${MAIL_ENABLED:false}
security.guest.disabled=${SECURITY_GUEST_DISABLED:false}
