/*
 *    Copyright 2015 West Coast Informatics, LLC
 */
package com.wci.umls.server.jpa.algo.insert;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.net.InetAddress;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Properties;
import java.util.Set;
import java.util.UUID;

import com.wci.umls.server.model.algo.AlgorithmParameter;
import com.wci.umls.server.model.algo.ValidationResult;
import com.wci.umls.server.helpers.ConfigUtility;
import com.wci.umls.server.helpers.PropertyUtility;
import com.wci.umls.server.helpers.QueryType;
import com.wci.umls.server.jpa.model.ValidationResultJpa;
import com.wci.umls.server.jpa.algo.AbstractInsertMaintReleaseAlgorithm;
import com.wci.umls.server.model.meta.Terminology;
import com.wci.umls.server.model.workflow.Checklist;

/**
 * Implementation of an algorithm to create report table checklists.
 */
public class ReportChecklistAlgorithm
    extends AbstractInsertMaintReleaseAlgorithm {

  /**
   * Instantiates an empty {@link ReportChecklistAlgorithm}.
   * @throws Exception if anything goes wrong
   */
  public ReportChecklistAlgorithm() throws Exception {
    super();
    setActivityId(UUID.randomUUID().toString());
    setWorkId("REPORTCHECKLIST");
    setLastModifiedBy("admin");
  }

  /**
   * Check preconditions.
   *
   * @return the validation result
   * @throws Exception the exception
   */
  /* see superclass */
  @Override
  public ValidationResult checkPreconditions() throws Exception {

    ValidationResult validationResult = new ValidationResultJpa();

    if (getProject() == null) {
      throw new Exception(
          "Report Checklist Algorithm requires a project to be set");
    }

    // Check the input directories

    final String srcFullPath =
        PropertyUtility.getProperties().getProperty("source.data.dir")
            + File.separator + getProcess().getInputPath();

    setSrcDirFile(new File(srcFullPath));
    if (!getSrcDirFile().exists()) {
      throw new Exception("Specified input directory does not exist");
    }

    return validationResult;
  }

  /**
   * Compute.
   *
   * @throws Exception the exception
   */
  /* see superclass */
  @Override
  public void compute() throws Exception {
    logInfo("Starting " + getName());

    // No molecular actions will be generated by this algorithm
    setMolecularActionFlag(false);

    try {

      logInfo("  Creating the report table checklists");
      commitClearBegin();

      final File outputFile =
          new File(getSrcDirFile(), "reportChecklistResults.txt");
      String server = InetAddress.getLocalHost().getHostName();
      
      final PrintWriter out =
          new PrintWriter(new FileWriter(outputFile, StandardCharsets.UTF_8));
      
      final String insertionEnvironment = getInsertionEnvironment(server);
      final String insertionType = getInsertionType(insertionEnvironment);

      out.println("The " + insertionType + " insertion of "
          + getProcess().getTerminology() + "_" + getProcess().getVersion()
          + " is complete on " + insertionEnvironment
          + ". The counts are as follows:");
      out.println("");
      
      // Get all terminologies referenced in the sources.src file
      Set<Terminology> terminologies = getReferencedTerminologies();

      setSteps(terminologies.size());

      // For each terminology, create four checklists
      for (final Terminology terminology : terminologies) {
        final String term = terminology.getTerminology();
        final String version = terminology.getVersion();

        checkCancel();

        // All four queries start with the same clauses
        final String queryPrefix =
            "select c.id as conceptId from ConceptJpa c join c.atoms a "
                + "where c.terminology=:projectTerminology and "
                + "a.terminology='" + term + "' and a.version='" + version
                + "'";

        if (getProcess().getTerminology().contains(term) && getProcess().getVersion().contains(version)) {      	
        	out.println("");
        }
        
        Checklist checklist = computeChecklist(getProject(),
            queryPrefix + " AND a.workflowStatus='NEEDS_REVIEW'", QueryType.JPQL,
            "chk_" + term + "_" + version + "_NEEDS_REVIEW", null, true);
        String result = "Created chk_" + term + "_" + version
            + "_NEEDS_REVIEW checklist, containing "
            + checklist.getTrackingRecords().size() + " tracking records.";
        logInfo("  " + result);
        if (checklist.getTrackingRecords().size() > 0) {
        	out.println(result);
        }
        commitClearBegin();

        checklist = computeChecklist(getProject(),
            queryPrefix + " AND a.workflowStatus='DEMOTION'", QueryType.JPQL,
            "chk_" + term + "_" + version + "_DEMOTION", null, true);
        result = "Created chk_" + term + "_" + version
            + "_DEMOTION checklist, containing "
            + checklist.getTrackingRecords().size() + " tracking records.";
        logInfo("  " + result);
        if (checklist.getTrackingRecords().size() > 0) {
        	out.println(result);
        }
        commitClearBegin();

        checklist = computeChecklist(getProject(),
            queryPrefix
                + " AND (a.workflowStatus='READY_FOR_PUBLICATION' OR a.workflowStatus='PUBLISHED')",
            QueryType.JPQL,
            "chk_" + term + "_" + version + "_READY_FOR_PUBLICATION", null,
            true);
        result = "Created chk_" + term + "_" + version
            + "_READY_FOR_PUBLICATION checklist, containing "
            + checklist.getTrackingRecords().size() + " tracking records.";
        logInfo("  " + result);
        if (getProcess().getTerminology().contains(term) && getProcess().getTerminology().contains(version)) {
        	out.println(result);
        }
        commitClearBegin();

        checklist = computeChecklist(getProject(),
            queryPrefix + " AND a.lastModifiedBy like 'ENG-%'", QueryType.JPQL,
            "chk_" + term + "_" + version + "_MIDMERGES", null, true);
        result = "Created chk_" + term + "_" + version
            + "_MIDMERGES checklist, containing "
            + checklist.getTrackingRecords().size() + " tracking records.";
        logInfo("  " + result);
        if (checklist.getTrackingRecords().size() > 0) {
        	out.println(result);
        }
        commitClearBegin();

        // Update the progress
        updateProgress();
        if (getProcess().getTerminology().contains(term) && getProcess().getVersion().contains(version)) {      	
        	out.println("");
        }
        logInfo("");
      }

      commitClearBegin();

      logInfo("Finished " + getName());
      out.close();

      // Now directly sending to meme-team@westcoastinformatics.com
      // Process feedback email is going to support-meme@westcoastinformatics.com
      final String recipients = "meme-team@westcoastinformatics.com";

      if (!ConfigUtility.isEmpty(recipients)) {
        final Properties config = PropertyUtility.getProperties();
        String from;
        if (config.containsKey("mail.smtp.from")) {
          from = config.getProperty("mail.smtp.from");
        } else {
          from = config.getProperty("mail.smtp.user");
        }


        ConfigUtility.sendEmail(
            "Report Checklist Algorithm Complete for "
                + ("test".equals(insertionType) ? "Test " : "") + "Process: "
                + getProcess().getName(),
            from, recipients, 
            "Checklist counts attached for " + getProcess().getTerminology()
                + "_" + getProcess().getVersion() + " " + insertionType
                + " insertion.",
            config,
            outputFile.getAbsolutePath());
      }

    } catch (

    Exception e) {
      logError("Unexpected problem - " + e.getMessage());
      throw e;
    }

  }

  /**
   * Returns the display environment for insertion report emails.
   *
   * @param server the local server hostname
   * @return the display environment
   */
  private String getInsertionEnvironment(final String server) {

    final Properties config = PropertyUtility.getProperties();
    final String configuredEnvironment =
        config.getProperty("insertion.report.environment");
    if (!ConfigUtility.isEmpty(configuredEnvironment)) {
      return configuredEnvironment;
    }

    final String baseUrlEnvironment =
        getEnvironmentFromBaseUrl(config.getProperty("base.url"));
    if (!ConfigUtility.isEmpty(baseUrlEnvironment)) {
      return baseUrlEnvironment;
    }

    if (server.startsWith("ncias-q3795-c")
        || server.startsWith("ncias-q3794-c")
        || server.startsWith("ncias-d3777-c")) {
      return "meme-test";
    }
    return "meme-edit";
  }

  /**
   * Returns the insertion type label for the display environment.
   *
   * @param insertionEnvironment the display environment
   * @return the insertion type
   */
  private String getInsertionType(final String insertionEnvironment) {
    return insertionEnvironment.contains("test") ? "test" : "real";
  }

  /**
   * Derives a friendly environment label from the configured base URL.
   *
   * @param baseUrl the base URL
   * @return the environment label, or null
   */
  private String getEnvironmentFromBaseUrl(final String baseUrl) {

    if (ConfigUtility.isEmpty(baseUrl)) {
      return null;
    }

    try {
      final String host = new URI(baseUrl).getHost();
      if (ConfigUtility.isEmpty(host) || "localhost".equals(host)) {
        return null;
      }
      final String label = host.split("\\.")[0];
      return label.startsWith("meme-") ? label : null;
    } catch (Exception e) {
      return null;
    }
  }

  /**
   * Reset.
   *
   * @throws Exception the exception
   */
  /* see superclass */
  @Override
  public void reset() throws Exception {
    logInfo("Starting RESET " + getName());
    // n/a - No reset
    logInfo("Finished RESET " + getName());
  }

  /* see superclass */
  @Override
  public void checkProperties(Properties p) throws Exception {
    // n/a
  }

  /* see superclass */
  @Override
  public void setProperties(Properties p) throws Exception {
    // n/a
  }

  /**
   * Returns the parameters.
   *
   * @return the parameters
   */
  /* see superclass */
  @Override
  public List<AlgorithmParameter> getParameters() throws Exception {
    final List<AlgorithmParameter> params = super.getParameters();

    return params;
  }

  @Override
  public String getDescription() {
    return "Generates standard report table checklists for the insertion.";
  }
}
